server:
  port: 8080
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name:
  #配置发送方信息
  mail:
    host: smtp.qq.com
    username: 3301846209@qq.com #邮箱地址
    password: ninhygmkhjqgcgjg  #POP3/SMTP服务授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template: false
    check-template-location: false
  mvc:
    date-format: yyyy-MM-dd
mybatis:
   mapperLocations: classpath:/mapper/*.xml

